//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.8.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.ComponentModel;
using System.Runtime.Serialization;
using System.Collections.Generic;

namespace NWService.Dtos.DtoClasses
{ 
	/// <summary> DTO class which is derived from the entity 'Order'.</summary>
	[Serializable]
	[DataContract]
	public partial class Order
	{
		/// <summary>Gets or sets the CustomerId field. Derived from Entity Model Field 'Order.CustomerId (FK)'</summary>
		[DataMember]
		public System.String CustomerId { get; set; }
		/// <summary>Gets or sets the EmployeeId field. Derived from Entity Model Field 'Order.EmployeeId (FK)'</summary>
		[DataMember]
		public Nullable<System.Int32> EmployeeId { get; set; }
		/// <summary>Gets or sets the Freight field. Derived from Entity Model Field 'Order.Freight'</summary>
		[DataMember]
		public Nullable<System.Decimal> Freight { get; set; }
		/// <summary>Gets or sets the OrderDate field. Derived from Entity Model Field 'Order.OrderDate'</summary>
		[DataMember]
		public Nullable<System.DateTime> OrderDate { get; set; }
		/// <summary>Gets or sets the OrderDetails field. </summary>
		[DataMember]
		public List<OrderTypes.OrderDetail> OrderDetails { get; set; }
		/// <summary>Gets or sets the OrderId field. Derived from Entity Model Field 'Order.OrderId'</summary>
		[DataMember]
		public System.Int32 OrderId { get; set; }
		/// <summary>Gets or sets the RequiredDate field. Derived from Entity Model Field 'Order.RequiredDate'</summary>
		[DataMember]
		public Nullable<System.DateTime> RequiredDate { get; set; }
		/// <summary>Gets or sets the ShipAddress field. Derived from Entity Model Field 'Order.ShipAddress'</summary>
		[DataMember]
		public System.String ShipAddress { get; set; }
		/// <summary>Gets or sets the ShipCity field. Derived from Entity Model Field 'Order.ShipCity'</summary>
		[DataMember]
		public System.String ShipCity { get; set; }
		/// <summary>Gets or sets the ShipCountry field. Derived from Entity Model Field 'Order.ShipCountry'</summary>
		[DataMember]
		public System.String ShipCountry { get; set; }
		/// <summary>Gets or sets the ShipName field. Derived from Entity Model Field 'Order.ShipName'</summary>
		[DataMember]
		public System.String ShipName { get; set; }
		/// <summary>Gets or sets the ShippedDate field. Derived from Entity Model Field 'Order.ShippedDate'</summary>
		[DataMember]
		public Nullable<System.DateTime> ShippedDate { get; set; }
		/// <summary>Gets or sets the ShipPostalCode field. Derived from Entity Model Field 'Order.ShipPostalCode'</summary>
		[DataMember]
		public System.String ShipPostalCode { get; set; }
		/// <summary>Gets or sets the ShipRegion field. Derived from Entity Model Field 'Order.ShipRegion'</summary>
		[DataMember]
		public System.String ShipRegion { get; set; }
		/// <summary>Gets or sets the ShipVia field. Derived from Entity Model Field 'Order.ShipVia (FK)'</summary>
		[DataMember]
		public Nullable<System.Int32> ShipVia { get; set; }
	}

	namespace OrderTypes
	{
		/// <summary> DTO class which is derived from the entity 'OrderDetail (OrderDetails)'.</summary>
		[Serializable]
		[DataContract]
		public partial class OrderDetail
		{
			/// <summary>Gets or sets the Discount field. Derived from Entity Model Field 'OrderDetail.Discount'</summary>
			[DataMember]
			public System.Single Discount { get; set; }
			/// <summary>Gets or sets the ProductId field. Derived from Entity Model Field 'OrderDetail.ProductId (FK)'</summary>
			[DataMember]
			public System.Int32 ProductId { get; set; }
			/// <summary>Gets or sets the Quantity field. Derived from Entity Model Field 'OrderDetail.Quantity'</summary>
			[DataMember]
			public System.Int16 Quantity { get; set; }
			/// <summary>Gets or sets the UnitPrice field. Derived from Entity Model Field 'OrderDetail.UnitPrice'</summary>
			[DataMember]
			public System.Decimal UnitPrice { get; set; }
		}
	}

}




