//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.9.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: Tuesday, 1 February 2022 16:05:06
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using SD.LLBLGen.Pro.Examples.Auditing.FactoryClasses;
using SD.LLBLGen.Pro.Examples.Auditing.DaoClasses;
using SD.LLBLGen.Pro.Examples.Auditing.RelationClasses;
using SD.LLBLGen.Pro.Examples.Auditing.HelperClasses;
using SD.LLBLGen.Pro.Examples.Auditing.CollectionClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace SD.LLBLGen.Pro.Examples.Auditing.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END
	/// <summary>Entity class which represents the entity 'Region'. <br/><br/></summary>
	[Serializable]
	public partial class RegionEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END	
	{
		private SD.LLBLGen.Pro.Examples.Auditing.CollectionClasses.TerritoryCollection	_territories;

		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END
		private static RegionEntityStaticMetaData _staticMetaData = new RegionEntityStaticMetaData();
		private static RegionRelations _relationsFactory = new RegionRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name Territories</summary>
			public static readonly string Territories = "Territories";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class RegionEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public RegionEntityStaticMetaData()
			{
				SetEntityCoreInfo("RegionEntity", InheritanceHierarchyType.None, false, (int)SD.LLBLGen.Pro.Examples.Auditing.EntityType.RegionEntity, typeof(RegionEntity), typeof(RegionEntityFactory), false);
				AddNavigatorMetaData<RegionEntity, SD.LLBLGen.Pro.Examples.Auditing.CollectionClasses.TerritoryCollection>("Territories", a => a._territories, (a, b) => a._territories = b, a => a.Territories, () => new RegionRelations().TerritoryEntityUsingRegionId, typeof(TerritoryEntity), (int)SD.LLBLGen.Pro.Examples.Auditing.EntityType.TerritoryEntity);
			}
		}
		
		/// <summary>Static ctor</summary>
		static RegionEntity()
		{
		}

		/// <summary>CTor</summary>
		public RegionEntity() :base()
		{
			InitClassEmpty(null);
		}
		
		/// <summary>CTor</summary>
		/// <param name="regionId">PK value for Region which data should be fetched into this Region object</param>
		public RegionEntity(System.Int32 regionId)
		{
			InitClassFetch(regionId, null, null);
		}

		/// <summary>CTor</summary>
		/// <param name="regionId">PK value for Region which data should be fetched into this Region object</param>
		/// <param name="prefetchPathToUse">the PrefetchPath which defines the graph of objects to fetch as well</param>
		public RegionEntity(System.Int32 regionId, IPrefetchPath prefetchPathToUse)
		{
			InitClassFetch(regionId, null, prefetchPathToUse);
		}

		/// <summary>CTor</summary>
		/// <param name="regionId">PK value for Region which data should be fetched into this Region object</param>
		/// <param name="validator">The custom validator object for this RegionEntity</param>
		public RegionEntity(System.Int32 regionId, IValidator validator)
		{
			InitClassFetch(regionId, validator, null);
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected RegionEntity(SerializationInfo info, StreamingContext context):base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}



		/// <summary>Fetches the contents of this entity from the persistent storage using the primary key.</summary>
		/// <param name="regionId">PK value for Region which data should be fetched into this Region object</param>
		/// <returns>True if succeeded, false otherwise.</returns>
		public bool FetchUsingPK(System.Int32 regionId)
		{
			return FetchUsingPK(regionId, null, null, null);
		}

		/// <summary>Fetches the contents of this entity from the persistent storage using the primary key.</summary>
		/// <param name="regionId">PK value for Region which data should be fetched into this Region object</param>
		/// <param name="prefetchPathToUse">the PrefetchPath which defines the graph of objects to fetch as well</param>
		/// <returns>True if succeeded, false otherwise.</returns>
		public bool FetchUsingPK(System.Int32 regionId, IPrefetchPath prefetchPathToUse)
		{
			return FetchUsingPK(regionId, prefetchPathToUse, null, null);
		}

		/// <summary>Fetches the contents of this entity from the persistent storage using the primary key.</summary>
		/// <param name="regionId">PK value for Region which data should be fetched into this Region object</param>
		/// <param name="prefetchPathToUse">the PrefetchPath which defines the graph of objects to fetch as well</param>
		/// <param name="contextToUse">The context to add the entity to if the fetch was succesful. </param>
		/// <returns>True if succeeded, false otherwise.</returns>
		public bool FetchUsingPK(System.Int32 regionId, IPrefetchPath prefetchPathToUse, Context contextToUse)
		{
			return FetchUsingPK(regionId, prefetchPathToUse, contextToUse, null);
		}

		/// <summary>Fetches the contents of this entity from the persistent storage using the primary key.</summary>
		/// <param name="regionId">PK value for Region which data should be fetched into this Region object</param>
		/// <param name="prefetchPathToUse">the PrefetchPath which defines the graph of objects to fetch as well</param>
		/// <param name="contextToUse">The context to add the entity to if the fetch was succesful. </param>
		/// <param name="excludedIncludedFields">The list of IEntityField objects which have to be excluded or included for the fetch. 
		/// If null or empty, all fields are fetched (default). If an instance of ExcludeIncludeFieldsList is passed in and its ExcludeContainedFields property
		/// is set to false, the fields contained in excludedIncludedFields are kept in the query, the rest of the fields in the query are excluded.</param>
		/// <returns>True if succeeded, false otherwise.</returns>
		public bool FetchUsingPK(System.Int32 regionId, IPrefetchPath prefetchPathToUse, Context contextToUse, ExcludeIncludeFieldsList excludedIncludedFields)
		{
			return Fetch(regionId, prefetchPathToUse, contextToUse, excludedIncludedFields);
		}

		/// <inheritdoc/>
		public override bool Refetch()
		{
			return Fetch(this.RegionId, null, null, null);
		}

		/// <summary>Retrieves all related entities of type 'TerritoryEntity' using a relation of type '1:n'.</summary>
		/// <param name="forceFetch">if true, it will discard any changes currently in the collection and will rerun the complete query instead</param>
		/// <returns>Filled collection with all related entities of type 'TerritoryEntity'</returns>
		public SD.LLBLGen.Pro.Examples.Auditing.CollectionClasses.TerritoryCollection GetMultiTerritories(bool forceFetch)
		{
			return GetMultiTerritories(forceFetch, _territories.EntityFactoryToUse, null);
		}

		/// <summary>Retrieves all related entities of type 'TerritoryEntity' using a relation of type '1:n'.</summary>
		/// <param name="forceFetch">if true, it will discard any changes currently in the collection and will rerun the complete query instead</param>
		/// <param name="filter">Extra filter to limit the resultset.</param>
		/// <returns>Filled collection with all related entities of type 'TerritoryEntity'</returns>
		public SD.LLBLGen.Pro.Examples.Auditing.CollectionClasses.TerritoryCollection GetMultiTerritories(bool forceFetch, IPredicateExpression filter)
		{
			return GetMultiTerritories(forceFetch, _territories.EntityFactoryToUse, filter);
		}

		/// <summary>Retrieves all related entities of type 'TerritoryEntity' using a relation of type '1:n'.</summary>
		/// <param name="forceFetch">if true, it will discard any changes currently in the collection and will rerun the complete query instead</param>
		/// <param name="entityFactoryToUse">The entity factory to use for the GetMultiManyToOne() routine.</param>
		/// <returns>Filled collection with all related entities of the type constructed by the passed in entity factory</returns>
		public SD.LLBLGen.Pro.Examples.Auditing.CollectionClasses.TerritoryCollection GetMultiTerritories(bool forceFetch, IEntityFactory entityFactoryToUse)
		{
			return GetMultiTerritories(forceFetch, entityFactoryToUse, null);
		}

		/// <summary>Retrieves all related entities of type 'TerritoryEntity' using a relation of type '1:n'.</summary>
		/// <param name="forceFetch">if true, it will discard any changes currently in the collection and will rerun the complete query instead</param>
		/// <param name="entityFactoryToUse">The entity factory to use for the GetMultiManyToOne() routine.</param>
		/// <param name="filter">Extra filter to limit the resultset.</param>
		/// <returns>Filled collection with all related entities of the type constructed by the passed in entity factory</returns>
		public virtual SD.LLBLGen.Pro.Examples.Auditing.CollectionClasses.TerritoryCollection GetMultiTerritories(bool forceFetch, IEntityFactory entityFactoryToUse, IPredicateExpression filter)
		{
			return PerformMultiEntityLazyLoading<SD.LLBLGen.Pro.Examples.Auditing.CollectionClasses.TerritoryCollection>("Territories", forceFetch, entityFactoryToUse, (c,r)=>c.GetMultiManyToOne(this, filter));
		}

		/// <summary>Sets the collection parameters for the collection for 'Territories'. These settings will be taken into account
		/// when the property Territories is requested or GetMultiTerritories is called.</summary>
		/// <param name="maxNumberOfItemsToReturn"> The maximum number of items to return. When set to 0, this parameter is ignored</param>
		/// <param name="sortClauses">The order by specifications for the sorting of the resultset. When not specified (null), no sorting is applied.</param>
		public virtual void SetCollectionParametersTerritories(long maxNumberOfItemsToReturn, ISortExpression sortClauses)
		{
			_territories.SortClauses=sortClauses;
			_territories.MaxNumberOfItemsToReturn=maxNumberOfItemsToReturn;
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validatorToUse">Validator to use.</param>
		private void InitClassEmpty(IValidator validatorToUse)
		{
			OnInitializing();
			this.Fields = CreateFields();
			this.Validator = validatorToUse;
			InitClassMembers();

			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitialized();
		}		

		/// <summary>Initializes the the entity and fetches the data related to the entity in this entity.</summary>
		/// <param name="regionId">PK value for Region which data should be fetched into this Region object</param>
		/// <param name="validator">The validator object for this RegionEntity</param>
		/// <param name="prefetchPathToUse">the PrefetchPath which defines the graph of objects to fetch as well</param>
		private void InitClassFetch(System.Int32 regionId, IValidator validator, IPrefetchPath prefetchPathToUse)
		{
			OnInitializing();
			this.Validator = validator;
			this.Fields = CreateFields();
			InitClassMembers();	
			Fetch(regionId, prefetchPathToUse, null, null);

			// __LLBLGENPRO_USER_CODE_REGION_START InitClassFetch
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitialized();
		}

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			_territories = new SD.LLBLGen.Pro.Examples.Auditing.CollectionClasses.TerritoryCollection();
			_territories.SetContainingEntityInfo(this, "Region");
			PerformDependencyInjection();

			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END
			OnInitClassMembersComplete();
		}


		/// <summary>Fetches the entity from the persistent storage. Fetch simply reads the entity into an EntityFields object. </summary>
		/// <param name="regionId">PK value for Region which data should be fetched into this Region object</param>
		/// <param name="prefetchPathToUse">the PrefetchPath which defines the graph of objects to fetch as well</param>
		/// <param name="contextToUse">The context to add the entity to if the fetch was succesful. </param>
		/// <param name="excludedIncludedFields">The list of IEntityField objects which have to be excluded or included for the fetch. 
		/// If null or empty, all fields are fetched (default). If an instance of ExcludeIncludeFieldsList is passed in and its ExcludeContainedFields property
		/// is set to false, the fields contained in excludedIncludedFields are kept in the query, the rest of the fields in the query are excluded.</param>
		/// <returns>True if succeeded, false otherwise.</returns>
		private bool Fetch(System.Int32 regionId, IPrefetchPath prefetchPathToUse, Context contextToUse, ExcludeIncludeFieldsList excludedIncludedFields)
		{
			try
			{
				OnFetch();
				this.Fields[(int)RegionFieldIndex.RegionId].ForcedCurrentValueWrite(regionId);
				CreateDAOInstance().FetchExisting(this, this.Transaction, prefetchPathToUse, contextToUse, excludedIncludedFields);
				return (this.Fields.State == EntityState.Fetched);
			}
			finally
			{
				OnFetchComplete();
			}
		}

		/// <summary>Creates the DAO instance for this type</summary>
		/// <returns></returns>
		protected override IDao CreateDAOInstance() { return DAOFactory.CreateRegionDAO(); }
		
		/// <summary>Gets the entity static meta data instance from the generated type.</summary>
		/// <returns>The instance requested</returns>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() { return _staticMetaData; }
		
		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static RegionRelations Relations { get { return _relationsFactory; } }


		/// <summary>Creates a new PrefetchPathElement object which contains all the information to prefetch the related entities of type 'Territory' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement implementation.</returns>
		public static IPrefetchPathElement PrefetchPathTerritories { get { return _staticMetaData.GetPrefetchPathElement("Territories", new SD.LLBLGen.Pro.Examples.Auditing.CollectionClasses.TerritoryCollection()); } }


		/// <summary>The RegionDescription property of the Entity Region<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Region"."RegionDescription"<br/>
		/// Table field type characteristics (type, precision, scale, length): NChar, 0, 0, 50<br/>
		/// Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String RegionDescription
		{
			get { return (System.String)GetValue((int)RegionFieldIndex.RegionDescription, true); }
			set	{ SetValue((int)RegionFieldIndex.RegionDescription, value, true); }
		}

		/// <summary>The RegionId property of the Entity Region<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Region"."RegionID"<br/>
		/// Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0<br/>
		/// Table field behavior characteristics (is nullable, is PK, is identity): false, true, false</remarks>
		public virtual System.Int32 RegionId
		{
			get { return (System.Int32)GetValue((int)RegionFieldIndex.RegionId, true); }
			set	{ SetValue((int)RegionFieldIndex.RegionId, value, true); }
		}

		/// <summary>Retrieves all related entities of type 'TerritoryEntity' using a relation of type '1:n'.<br/><br/></summary>
		public virtual SD.LLBLGen.Pro.Examples.Auditing.CollectionClasses.TerritoryCollection Territories { get { return GetMultiTerritories(false); } }

		/// <summary>Gets / sets the lazy loading flag for Territories. When set to true, Territories is always refetched from the 
		/// persistent storage. When set to false, the data is only fetched the first time Territories is accessed. You can always execute/ a forced fetch by calling GetMultiTerritories(true).</summary>
		[Browsable(false)]
		public bool AlwaysFetchTerritories
		{
			get	{ return GetAlwaysFetchValueForNavigator("Territories"); }
			set	{ SetAlwaysFetchValueForNavigator("Territories", value); }	
		}		
				
		/// <summary>Gets / Sets the lazy loading flag if the property Territories already has been fetched. Setting this property to false when Territories has been fetched
		/// will clear the Territories collection well. Setting this property to true while Territories hasn't been fetched disables lazy loading for Territories</summary>
		[Browsable(false)]
		public bool AlreadyFetchedTerritories
		{
			get { return GetAlreadyFetchedValueForNavigator("Territories");}
			set { SetAlreadyFetchedValueForNavigator("Territories", value, true);}
		}



		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END

	}
}

namespace SD.LLBLGen.Pro.Examples.Auditing
{
	public enum RegionFieldIndex
	{
		///<summary>RegionDescription. </summary>
		RegionDescription,
		///<summary>RegionId. </summary>
		RegionId,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace SD.LLBLGen.Pro.Examples.Auditing.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: Region. </summary>
	public partial class RegionRelations: RelationFactory
	{
		/// <summary>Returns a new IEntityRelation object, between RegionEntity and TerritoryEntity over the 1:n relation they have, using the relation between the fields: Region.RegionId - Territory.RegionId</summary>
		public virtual IEntityRelation TerritoryEntityUsingRegionId
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "Territories", true, new[] { RegionFields.RegionId, TerritoryFields.RegionId }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticRegionRelations
	{
		internal static readonly IEntityRelation TerritoryEntityUsingRegionIdStatic = new RegionRelations().TerritoryEntityUsingRegionId;

		/// <summary>CTor</summary>
		static StaticRegionRelations() { }
	}
}
