//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


public partial class HelperControls_DateTextBox {
    protected System.Web.UI.WebControls.TextBox tbxMonth;
    protected System.Web.UI.WebControls.RangeValidator valMonth;
    protected System.Web.UI.WebControls.TextBox tbxDay;
    protected System.Web.UI.WebControls.RangeValidator valDay;
    protected System.Web.UI.WebControls.TextBox tbxYear;
    protected System.Web.UI.WebControls.RegularExpressionValidator valYear;
    protected System.Web.UI.WebControls.Label lblDateDescription;
}
