//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.9.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using Northwind.SSDAL.EntityClasses;
using Northwind.SSDAL.HelperClasses;
using Northwind.SSDAL.FactoryClasses;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace Northwind.SSDAL.DaoClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END
	/// <summary>General DAO class for the Group Entity. It will perform database oriented actions for a entity of type 'GroupEntity'.</summary>
	public partial class GroupDAO : CommonDaoBase
	{
		/// <summary>CTor</summary>
		public GroupDAO() : base(InheritanceHierarchyType.None, "GroupEntity", new GroupEntityFactory()) { }





		// __LLBLGENPRO_USER_CODE_REGION_START CustomDAOCode
		// __LLBLGENPRO_USER_CODE_REGION_END

	}
}
