//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.9.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using Northwind.SSDAL.EntityClasses;
using Northwind.SSDAL.HelperClasses;
using Northwind.SSDAL.FactoryClasses;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace Northwind.SSDAL.DaoClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END
	/// <summary>General DAO class for the Supplier Entity. It will perform database oriented actions for a entity of type 'SupplierEntity'.</summary>
	public partial class SupplierDAO : CommonDaoBase
	{
		/// <summary>CTor</summary>
		public SupplierDAO() : base(InheritanceHierarchyType.None, "SupplierEntity", new SupplierEntityFactory()) { }





		// __LLBLGENPRO_USER_CODE_REGION_START CustomDAOCode
		// __LLBLGENPRO_USER_CODE_REGION_END

	}
}
