//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


public partial class Controls_ViewRelatedToCustomer {
    protected Controls_ListCustomerCustomerDemoInstances laCustomerCustomerDemo;
    protected Controls_ListOrderInstances laOrders;
    protected Controls_ListCustomerDemographyInstances laCustomerDemographicsCollectionViaCustomerCustomerDemo;
}
